### ISSUE TITLE
Getting error on IPad - Unsupported JWK algorithm RSA-OAEP-256

### ISSUE THREAD

**Issue by tejaswibharadwajp** [CyberSource/cybersource-flex-samples#20]
Hi,
I am getting the error if I used this package on iPad Air. at createToken method.. I am on latest safari browser and I have tried with '@cybersource/flex-sdk-web/legacy' as well. Could you please assist me on this.

**Comment by rhidianj** [comment]
Older versions of Safari do not support RSA OAEP with SHA256 mask generation function particularly well.

To address this, try using the “RsaOaep” Flex encryption type rather than “RsaOaep256”. For example:

•	https://github.com/CyberSource/cybersource-flex-samples/blob/master/java8/jsp-microform/src/main/java/com/cybersource/example/FlexKeyProvider.java, line 47 replace “EncryptionType.RsaOaep256” with “EncryptionType.RsaOaep”.
•	https://github.com/CyberSource/cybersource-flex-samples/blob/master/java8/jsp-microform/src/main/webapp/index.jsp, line 109 replace “rsaoaep256” with “rsaoaep”.
